import type { DebloatPreset } from "./presets-types";

export type { DebloatPreset };

export const DEBLOAT_PRESETS: DebloatPreset[] = [
  {
    brand: "Universal: Kunci Update OTA (Semua Merek)",
    packages: [
      { name: "com.sec.android.soagent", description: "Samsung System OS Agent (OTA Core)", safe_to_remove: true },
      { name: "com.wssyncmldm", description: "Samsung Device Management Software Update", safe_to_remove: true },
      { name: "com.samsung.sdm", description: "Samsung Software Update Service", safe_to_remove: true },
      { name: "com.samsung.sdm.sdmviewer", description: "Samsung SDM Viewer", safe_to_remove: true },
      { name: "com.sec.android.systemupdate", description: "Samsung System Update Client", safe_to_remove: true },
      { name: "com.android.updater", description: "Xiaomi / POCO / Redmi System Updater", safe_to_remove: true },
      { name: "com.coloros.sau", description: "OPPO / Realme Software Auto Update (SAU)", safe_to_remove: true },
      { name: "com.coloros.sauhelper", description: "OPPO / Realme SAU Helper", safe_to_remove: true },
      { name: "com.oppo.ota", description: "OPPO OTA System Update", safe_to_remove: true },
      { name: "com.oplus.ota", description: "OnePlus / Oplus OTA System Update", safe_to_remove: true },
      { name: "com.coloros.ota", description: "ColorOS OTA System Update", safe_to_remove: true },
      { name: "com.bbk.updater", description: "Vivo / iQOO System Updater", safe_to_remove: true },
      { name: "com.vivo.abe", description: "Vivo Android Background Engine Auto Update", safe_to_remove: true },
      { name: "com.transsion.systemupdate", description: "Infinix / Tecno System Update", safe_to_remove: true },
      { name: "com.transsion.ota", description: "Infinix / Tecno OTA Core", safe_to_remove: true },
      { name: "com.transsion.plat.appupdate", description: "Transsion Internal App Updater", safe_to_remove: true },
      { name: "com.huawei.android.hwouc", description: "Huawei / Honor Over-The-Air Update Center", safe_to_remove: true },
    ],
  },
  {
    brand: "Universal: Anti-Iklan & Pop-Up Operator",
    packages: [
      { name: "com.android.simappdialog", description: "SIM App Dialog (Popup Iklan Modal)", safe_to_remove: true },
      { name: "com.mediatek.simprocessor", description: "MTK SIM Processor (Push Event SIM)", safe_to_remove: true },
      { name: "com.android.cellbroadcastreceiver", description: "Cell Broadcast (Spam Siaran Operator)", safe_to_remove: true },
      { name: "com.google.android.cellbroadcastreceiver", description: "Google Cell Broadcast (Pesan Siaran)", safe_to_remove: true },
      { name: "com.android.stk", description: "SIM Toolkit 1 (Menu Kartu SIM Utama)", safe_to_remove: true },
      { name: "com.android.stk2", description: "SIM Toolkit 2 (Menu Kartu SIM Kedua)", safe_to_remove: true },
      { name: "com.geniex.vsimhelper", description: "GenieX vSIM Helper (Push Promo Roaming)", safe_to_remove: true },
    ],
  },
  {
    brand: "Xiaomi / POCO / Redmi",
    packages: [
      { name: "com.miui.analytics", description: "MIUI Analytics", safe_to_remove: true },
      { name: "com.miui.msa.global", description: "MSA Ads", safe_to_remove: true },
      { name: "com.xiaomi.mipicks", description: "GetApps", safe_to_remove: true },
      { name: "com.mi.globalbrowser", description: "Mi Browser", safe_to_remove: true },
      { name: "com.miui.videoplayer", description: "Mi Video", safe_to_remove: true },
      { name: "com.miui.player", description: "Mi Music", safe_to_remove: true },
      { name: "com.xiaomi.glgm", description: "Games", safe_to_remove: true },
      { name: "com.miui.android.fashiongallery", description: "Wallpaper carousel", safe_to_remove: true },
    ],
  },
  {
    brand: "Samsung",
    packages: [
      { name: "com.samsung.android.bixby.agent", description: "Bixby", safe_to_remove: true },
      { name: "com.samsung.android.app.spage", description: "Bixby Home", safe_to_remove: true },
      { name: "com.samsung.android.game.gamehome", description: "Game Launcher", safe_to_remove: true },
      { name: "com.samsung.android.mateagent", description: "Galaxy Friends", safe_to_remove: true },
    ],
  },
  {
    brand: "OPPO / Realme",
    packages: [
      { name: "com.heytap.market", description: "App Market", safe_to_remove: true },
      { name: "com.oppo.market", description: "OPPO Market", safe_to_remove: true },
      { name: "com.realme.logtool", description: "Log tool", safe_to_remove: true },
    ],
  },
  {
    brand: "Vivo",
    packages: [
      { name: "com.vivo.appstore", description: "Vivo Store", safe_to_remove: true },
      { name: "com.vivo.browser", description: "Vivo Browser", safe_to_remove: true },
    ],
  },
  {
    brand: "Generic AOSP / Google / Facebook",
    packages: [
      { name: "com.android.adservices.api", description: "Android AdServices Ad Engine API", safe_to_remove: true },
      { name: "com.google.android.verifier", description: "Google Play Cloud Package Verifier (Fix Play Store stuck di Android 16+)", safe_to_remove: true },
      { name: "com.android.devicediagnostics", description: "Device Diagnostics & Telemetry", safe_to_remove: true },
      { name: "com.google.android.marvin.talkback", description: "Android Accessibility TalkBack", safe_to_remove: true },
      { name: "com.android.printspooler", description: "Android Print Spooler", safe_to_remove: true },
      { name: "com.google.android.printservice.recommendation", description: "Print Service Recommendation Plugin", safe_to_remove: true },
      { name: "com.google.android.apps.emojiwallpaper", description: "Emoji Wallpaper Generator", safe_to_remove: true },
      { name: "com.facebook.services", description: "Facebook Services", safe_to_remove: true },
      { name: "com.facebook.system", description: "Facebook System", safe_to_remove: true },
      { name: "com.facebook.appmanager", description: "Facebook App Manager", safe_to_remove: true },
      { name: "com.android.egg", description: "Android Easter Egg", safe_to_remove: true },
      { name: "com.android.bookmarkprovider", description: "Bookmark Provider", safe_to_remove: true },
    ],
  },
  {
    brand: "Infinix / Tecno / itel (XOS / HiOS)",
    packages: [
      { name: "com.transsion.magazineservice.xos", description: "Lockscreen Magazine & Wallpaper Carousel Ads", safe_to_remove: true },
      { name: "com.transsion.personalizedService.xos", description: "Targeted Ad Profiling & Tracking", safe_to_remove: true },
      { name: "com.transsion.statisticalsales", description: "Sales & Activation Telemetry", safe_to_remove: true },
      { name: "com.trassion.infinix.xclub", description: "XClub Community & Promotions", safe_to_remove: true },
      { name: "com.transsion.carlcare", description: "Carlcare Services", safe_to_remove: true },
      { name: "com.transsion.plat.appupdate", description: "Transsion Internal App Updater", safe_to_remove: true },
      { name: "com.transsion.tips", description: "XOS Tips & Feature Promos", safe_to_remove: true },
      { name: "com.transsion.guideservice", description: "User Service Guide", safe_to_remove: true },
      { name: "com.transsion.manualguide", description: "Digital User Manual", safe_to_remove: true },
      { name: "cn.wps.moffice.lite.abroad.transsion", description: "OEM WPS Office", safe_to_remove: true },
      { name: "com.facemoji.lite.transsion", description: "Facemoji OEM Keyboard", safe_to_remove: true },
      { name: "com.funbase.xradio", description: "Online Radio Streaming", safe_to_remove: true },
      { name: "com.transsion.cutepet", description: "CutePet Screen Animation", safe_to_remove: true },
      { name: "com.transsion.healthlife", description: "Transsion Health & Pedometer", safe_to_remove: true },
      { name: "com.transsion.wallet", description: "Transsion Wallet", safe_to_remove: true },
      { name: "com.transsion.letswitch", description: "LetSwitch Migration Tool", safe_to_remove: true },
      { name: "com.transsion.mobilecloner", description: "Mobile Cloner Tool", safe_to_remove: true },
      { name: "com.transsion.pcconnect", description: "PC Connect Tool", safe_to_remove: true },
      { name: "com.transsion.magicshow", description: "Magic Show", safe_to_remove: true },
    ],
  },
];
